### ISSUE TITLE
igsagent_service_call does not always destroy passed arguments list

### ISSUE THREAD

**Issue by LemortI2** [zeromq/ingescape#70] opened 2023-07-27 07:31 UTC

**Comment by Mathsoum** [comment] 2023-07-28 07:01
The problem is that in a majority of cases, everything goes according to plan and the arguments list passed to `igsagent_service_call` is destroyed (as the documentation said).

But, there is the case that the requested agent may have been destroyed while we were waiting for the mutex.  
In that case, the method returns without destroying the arguments. Since it's not the documented behavior, clients are not supposed to free that argument list and therefore it may cause a memory leak.

**Comment by Mathsoum** [comment] 2023-07-28 07:12
This issue has been addressed in the PR #71

**Closed** 2023-07-28 07:31 UTC
